### ISSUE TITLE
 Cannot find module "!style!css!./style.css"

### ISSUE THREAD

**Issue by PleaseTryAgain** [webpack/docs#101]
https://webpack.github.io/docs/tutorials/getting-started/
 The follow line of this tutorial should be changed, because ERROR INFOR has occured.
change to :  require("!style-loader!css-loader!./style.css");
after change this code can work well without error infor

![loader3](https://user-images.githubusercontent.com/12001845/28005131-95425af4-657b-11e7-9693-95c8a8d36652.png)

![loader](https://user-images.githubusercontent.com/12001845/28004939-61eefaaa-657a-11e7-966b-3711f385279a.png)

and this

![loader4](https://user-images.githubusercontent.com/12001845/28006548-59889fd0-6582-11e7-9660-8af699e0e6c2.png)

**Comment by ljqx** [comment]
You are using Webpack 3 but with doc for Webpack 1. See [Webpack 3 Doc - Loaders](https://webpack.js.org/concepts/loaders/)

**Comment by PleaseTryAgain** [comment]
@ljqx  I search webpack doc find this toturial. I will close this issue
