### ISSUE TITLE
Spam in the Wiki?

### ISSUE THREAD

**Issue by ChristianKienle** [webpack/docs#122]
Yesterday I noticed that there is some kind of malformed HTML in the docs:

![Screenshot 2019-08-07 at 08 46 36](https://user-images.githubusercontent.com/153225/62600745-f0e8e480-b8ef-11e9-89fa-ae8c902b15c4.png)

At first I was very concerned because I thought that someone from the Webpack team must have been compromised. How else should some kind of spam like this show up in the webpack docs?

Then I saw in the page history that the edit was made by a new user (registered 29 days ago) who is not part of the webpack team (thus no "hack" occurred). After seeing that I tried to edit any wiki page myself and I was able to do so. No checks required. I mean this is nice for contributors.

Because everyone is able to edit anything I took the liberty and removed the spam myself.

Just wanted to let you know about the issue and that this may cause ongoing problems because as far I know the edit history is also indexed by Google and thus a gold mine for spammers. Even deleting the spam will let them benefit in the long run.

Feel free to just close this issue if you think it is not a problem.

**Comment by sokra** [comment]
Thanks for removing it. I made the wiki readonly, since it's deprecated and very old anyway.
