### ISSUE TITLE
Remove 'devServer' option of webpack.config.js

### ISSUE THREAD

**Issue by necolas** [webpack/docs#23]
https://github.com/webpack/docs/wiki/configuration

Doesn't seem to be supported. Didn't want to try removing it from the wiki without confirmation.

**Comment by MrOrz** [comment]
More info added to the configuration page:
https://github.com/webpack/docs/wiki/configuration/_compare/255925b7a1631c766f842704bce6dc7007d3981d...7b31f408986516e5d1d8ccc51128d737c1d74055

And mentions `devServer`inside webpack-dev-server documentation:
https://github.com/webpack/docs/wiki/webpack-dev-server/_compare/0d116c9eb2121d52153f734d34a1713426958caa...4fbb038fcfddc54a84043c7b8335ecead9d0bc3a

**Comment by SpaceK33z** [comment]
Closing since it's documented clearly now.
