### ISSUE TITLE
I want to contribute to the Testing page, but can't find it. Am I in the right repo?

### ISSUE THREAD

**Issue by DanielApt** [webpack/docs#28]
I want to contribute to the [testing documentation](http://webpack.github.io/docs/testing.html). I can't seem to find it in this repo, yet this is the only docs repo I know of…

Could you please help?

**Comment by sokra** [comment]
At the top right corner is an "Edit" button. It's in the wiki...

**Comment by DanielApt** [comment]
Sorry, thanks about that!
