### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by totty90** [webpack/docs#29]
http://webpack.github.io/docs/library-and-externals.html

You have:

    output: {
        // export itself to a global var
        libraryTarget: "var"
        // name of the global var: "Foo"
        library: "Foo",
    },

The comma should be after `libraryTarget: "var"` and not after `library: "Foo"`.

**Comment by sokra** [comment]
you can fix it with the "Edit" button on the top right corner...

**Comment by totty90** [comment]
Done, I didn't knew that!
