### ISSUE TITLE
Does webpack-dev-server always serve bundle from memory?

### ISSUE THREAD

**Issue by gryzzly** [webpack/docs#32]
> Using this config webpack-dev-server will serve the static files in your build folder and watch your source files for changes. When changes are made the bundle will be recompiled. This modified bundle is served from memory at the relative path specified in publicPath (see API). It will not be written to your configured output directory. Where a bundle already exists at the same url path the bundle in memory will take precedence.

It doesn't seem to work the way it’s described here – when there's stuff in `build` folder, dev server still serves everything from memory. I also looked at source of [`webpack-dev-server`](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L53) **and** [`webpack-dev-middleware`](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L18) and it didn't seem that there's condition for **not** serving build from memory . An option to serve things directly from `output.path` folder would be helpful to test resulting production bundle.

I'd be happy to update the docs to reflect whatever goes on, wanted to get a confirmation that I'm correct.

**Comment by avindra** [comment]
Hi @gryzzly  : Have you discovered a viable way to serve directly from output.path?

**Comment by SpaceK33z** [comment]
> when there's stuff in build folder, dev server still serves everything from memory.

webpack-dev-server serves all assets from in-memory, but if you use the `contentBase` option (which defaults to your current working directory), it will serve those files from disk. The in-memory files are preferred above the contentBase files though.

**Comment by EKanadily** [comment]
that is sad because that way i can't use asp.net core app + webpack-dev-server because webpack-dev-server will server files from memory any updated contents will go to memory, asp.net core can't use them.

**Comment by dyardyGIT** [comment]
I am in same situation, wanting to use asp.net core but have files output so my views can reference.  What is best approach here?

**Comment by mzdr** [comment]
@dyardyGIT @EKanadily Give https://github.com/gajus/write-file-webpack-plugin a try. :)
