### ISSUE TITLE
webpack brand

### ISSUE THREAD

**Issue by jhnns** [webpack/docs#4]
This issue is dedicated to talk about the webpack brand (logo and design).

@shama created a first draft of the logo:

![webpack-logo1](https://f.cloud.github.com/assets/99604/1780319/93c67dda-686e-11e3-9229-8b4fb8432643.png)

**Comment by Alhadis** [comment]
Don't know if this will be of use to anybody, but I created a solid-coloured/silhouetted version of Webpack's logo for an [icons package](https://github.com/DanBrooker/file-icons/issues/304):

<img src="https://cloud.githubusercontent.com/assets/2346707/14160973/bf9f61ee-f72b-11e5-8259-2bcd1f507149.png" width="256" />

If anybody wants it, I've attached the [original Illustrator file](https://github.com/webpack/docs/files/196750/Webpack.zip). =)

**Comment by DenisIzmaylov** [comment]
Friends, I have a one question. Could I use a logo concept to visualize schema for PostCSS-to-JSS converter? Something like that:

![image](https://cloud.githubusercontent.com/assets/1690596/23369934/026ffde0-fd24-11e6-9a71-46793e2063d0.png)

_Source: https://github.com/axept/prejss_

**Comment by jhnns** [comment]
Is PreJSS using webpack? If yes, I think it would be appropriate if you also mention it. We allow every module in our ecosystem to use the logo.

If PreJSS is not related to webpack, I think it would be misleading to use the same logo.
