### ISSUE TITLE
Document the dll/dll-user plugins

### ISSUE THREAD

**Issue by wheresrhys** [webpack/docs#47]
They aren't mentioned at all in the documentation but look to provide a very powerful feature https://github.com/webpack/docs/search?utf8=%E2%9C%93&q=dll

![image](https://cloud.githubusercontent.com/assets/447559/11171471/e570d118-8be8-11e5-91c4-69e707ce8d20.png)

**Comment by shama** [comment]
Please note the docs are freely editable on: https://github.com/webpack/docs/wiki/contents Feel free to add or change anything you see fit! Thanks!

**Comment by wheresrhys** [comment]
Didn't realise. I will do after trying the plugins out

**Comment by SpaceK33z** [comment]
Closing in favor of https://github.com/webpack/webpack.js.org/issues/16
