### ISSUE TITLE
Is it possible to make webpack not write the result to disk?

### ISSUE THREAD

**Issue by thealjey** [webpack/docs#50]
Is it somehow possible to retrieve the resulting code and the respective sourcemap (from the `stats` object for example) and to instruct webpack not to write them to the file system at all?

**Comment by shama** [comment]
You can specify your own file system using `outputFileSystem` similar to what is being done here in [webpack-stream](https://github.com/shama/webpack-stream/blob/master/index.js#L135).

**Comment by thealjey** [comment]
Not very convenient, but if it's the only way...
Ideally, I think that if the user does not specify an `output` key in the config then webpack should simply return an object similar to `{code: ..., map: ...}` right in the `stats`.

But thanks anyways :smiley:

**Comment by shama** [comment]
I agree. The API you've suggested or a built-in stream interface would be nice and hopefully get implemented in the future. Thanks!
