### ISSUE TITLE
CLI option `--hot` not described in configuration docs

### ISSUE THREAD

**Issue by Download** [webpack/docs#55]
The documentation for configuration exhaustively describes all CLI / webpack.config.js options, but somehow option `hot` is not described there.

http://webpack.github.io/docs/configuration.html

**Comment by sokra** [comment]
It's not an option of the configuration.

It's an option of the webpack-dev-server.

http://webpack.github.io/docs/webpack-dev-server.html#webpack-dev-server-cli

**Comment by Download** [comment]
Ah! Thank you that explains it!
