### ISSUE TITLE
[Wiki] Component modules link returns 404

### ISSUE THREAD

**Issue by kohei-takata** [webpack/docs#56]
`Component modules` link in [https://github.com/webpack/docs/wiki/examples#module-styles](https://github.com/webpack/docs/wiki/examples#module-styles) returns 404 error.
`Component modules` link in [http://webpack.github.io/docs/examples.html#module-styles](http://webpack.github.io/docs/examples.html#module-styles) returns 404 error too.

There is no [https://github.com/webpack/webpack/tree/master/examples/component](https://github.com/webpack/webpack/tree/master/examples/component) directory.

**Comment by dhurlburtusa** [comment]
This is now fixed. Apparently, the content of http://webpack.github.io/docs/ is generated from the contents of the [wiki](https://github.com/webpack/docs/wiki) for https://github.com/webpack/docs.

It seems kind of dangerous to allow random github users, like myself, to edit the wiki without a review process.

Would someone with write access please close this if it is fixed to their liking?
