### ISSUE TITLE
Use dynamic script switch instead of `hot-dev-app.html`

### ISSUE THREAD

**Issue by davej** [webpack/docs#62]
Instead of having a separate html file for dev purposes you could do something like this in `app.html`:

```html
<script>
  const script = document.createElement('script');
  script.src = (process.env.HOT) ? 'http://localhost:3000/dist/app.js' : '../dist/app.js';
  document.write(script.outerHTML);
</script>
```

**Comment by chentsulin** [comment]
@davej I think you opened this issue at wrong place. Here is webpack/docs repo.

**Comment by davej** [comment]
@chentsulin Ha, too many github tabs open. :-)
