### ISSUE TITLE
Remove disqus comments and usage page?

### ISSUE THREAD

**Issue by shama** [webpack/docs#63]
@sokra The comments on the docs seemed to be just getting filled with comments dissatisfied with the docs rather than trying to actually help. What do you think about just removing the comments?

Also I think we should remove this page as usage is generally covered in the other parts of the docs and people are getting confused:

http://webpack.github.io/docs/usage.html

**Comment by dandv** [comment]
Comments are a great way for users to engage with the content, so I think we should keep the commenting feature.

I do agree we can delete obsolete comments, and Disqus has ways to do that. But the commenting mechanism itself, I think should be kept.

**Comment by SpaceK33z** [comment]
Closing since on the [new docs](https://github.com/webpack/webpack.js.org), the disqus comments are gone and the usage page has been reworked.
