### ISSUE TITLE
webpack-validator

### ISSUE THREAD

**Issue by jonathanewerner** [webpack/docs#65]
Hi,
i wrote a tool called [webpack-validator](https://github.com/jonathanewerner/webpack-validator) to help people configuring webpack by providing a [joi](https://github.com/hapijs/joi) schema for the webpack config object. I'm now exploring possibilities to hint users at the existence of this tool -- the webpack documentation seems like a good place i'd say. 
What do you think? Does this make sense? I'd be happy to PR if you'd point me to the location of the documentation where this would make sense.

**Comment by SpaceK33z** [comment]
Closing since webpack v2 has config validation built-in.
