### ISSUE TITLE
No documentation for `output.hashFunction`

### ISSUE THREAD

**Issue by bf** [webpack/docs#86]
I've read in the source that `hashFunction` can be set `sha256`, and webpack will use it to calculate `hash` and `chunkhash` values. Unfortunately I cannot find docs on `hashFunction` anywhere.

**Comment by SpaceK33z** [comment]
As the readme points out with capital letters, we are working on a complete doc rewrite (which is almost finished), https://github.com/webpack/webpack.js.org. If it is not documented on webpack.js.org, please create an issue on that repo.
